### ISSUE TITLE
ImportError: cannot import name 'keys' from 'securesystemslib'

### ISSUE THREAD

**Issue by adosar** [sigstore/gh-action-sigstore-python#126] opened 2024-05-07 12:13 UTC
**Description**

I am trying to sign my Python package with Sigstore but I get the following error:

```
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/runner/.local/lib/python3.10/site-packages/sigstore/__main__.py", line 20, in <module>
    from sigstore._cli import main
  File "/home/runner/.local/lib/python3.10/site-packages/sigstore/_cli.py", line 34, in <module>
    from sigstore._internal.rekor.client import (
  File "/home/runner/.local/lib/python3.10/site-packages/sigstore/_internal/rekor/__init__.py", line 19, in <module>
    from .client import RekorClient
  File "/home/runner/.local/lib/python3.10/site-packages/sigstore/_internal/rekor/client.py", line 33, in <module>
    from sigstore._internal.tuf import TrustUpdater
  File "/home/runner/.local/lib/python3.10/site-packages/sigstore/_internal/tuf.py", line 42, in <module>
    from tuf.ngclient import RequestsFetcher, Updater
  File "/home/runner/.local/lib/python3.10/site-packages/tuf/ngclient/__init__.py", line 14, in <module>
    from tuf.ngclient.updater import Updater
  File "/home/runner/.local/lib/python3.10/site-packages/tuf/ngclient/updater.py", line 48, in <module>
    from tuf.api.metadata import (
  File "/home/runner/.local/lib/python3.10/site-packages/tuf/api/metadata.py", line 56, in <module>
    from securesystemslib import keys as sslib_keys
ImportError: cannot import name 'keys' from 'securesystemslib' (/home/runner/.local/lib/python3.10/site-packages/securesystemslib/__init__.py)

Error: Process completed with exit code 1.
```

I am using the following `.yaml` file:
```yaml
name: Publish Python 🐍 distribution 📦 to PyPI

on: push

jobs:
  build:
    name: Build distribution 📦
    if: startsWith(github.ref, 'refs/tags/')  # only build on tag pushes
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"
    - name: Install pypa/build
      run: >-
        python3 -m
        pip install
        build
        --user
    - name: Build a binary wheel and a source tarball
      run: python3 -m build
    - name: Store the distribution packages
      uses: actions/upload-artifact@v4
      with:
        name: python-package-distributions
        path: dist/

  publish-to-pypi:
    name: Publish Python 🐍 distribution 📦 to PyPI
    if: startsWith(github.ref, 'refs/tags/')  # only publish to PyPI on tag pushes
    needs:
    - build
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/pymoxel  # Replace <package-name> with your PyPI project name
    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing

    steps:
    - name: Download all the dists
      uses: actions/download-artifact@v4
      with:
        name: python-package-distributions
        path: dist/
    - name: Publish distribution 📦 to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        skip-existing: true

  github-release:
    name: >-
      Sign the Python 🐍 distribution 📦 with Sigstore
      and upload them to GitHub Release
    needs:
    - publish-to-pypi
    runs-on: ubuntu-latest

    permissions:
      contents: write  # IMPORTANT: mandatory for making GitHub Releases
      id-token: write  # IMPORTANT: mandatory for sigstore

    steps:
    - name: Download all the dists
      uses: actions/download-artifact@v4
      with:
        name: python-package-distributions
        path: dist/
    - name: Sign the dists with Sigstore
      uses: sigstore/gh-action-sigstore-python@v1.2.3
      with:
        inputs: >-
          ./dist/*.tar.gz
          ./dist/*.whl
    - name: Create GitHub Release
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: >-
        gh release create
        '${{ github.ref_name }}'
        --repo '${{ github.repository }}'
        --notes ""
    - name: Upload artifact signatures to GitHub Release
      env:
        GITHUB_TOKEN: ${{ github.token }}
      # Upload to GitHub Release using the `gh` CLI.
      # `dist/` contains the built packages, and the
      # sigstore-produced signatures and certificates.
      run: >-
        gh release upload
        '${{ github.ref_name }}' dist/**
        --repo '${{ github.repository }}'
```

You can view the full GitHub action: [here](https://github.com/adosar/moxel/actions/runs/8984355898/job/24676129939).

**Comment by woodruffw** [comment] 2024-05-07 12:30
Thanks for the report @adosar! I believe this is a dupe of #122, i.e. the failure is caused by using a too-old version of the action. Could you try upgrading to a more recent version?

**Comment by woodruffw** [comment] 2024-05-07 21:17
That's because there is no version `v2.1.4` of the action (yet). The latest version is `v2.1.1`, as you can see here: https://github.com/sigstore/gh-action-sigstore-python/releases/tag/v2.1.1

**Closed as not planned** 2024-05-07 21:34 UTC
Labels: enhancement

**Comment by woodruffw** [comment] 2024-05-07 21:49
Understandable mistake! The versions are unfortunately very similar looking. Glad to hear you were able to get it working.
