### ISSUE TITLE
Sigstore v1.2.3 fails with import error

### ISSUE THREAD

**Issue by NotJoeMartinez** [sigstore/gh-action-sigstore-python#122] opened 2024-05-05 06:18 UTC
**Description**
My workflow file was using v1.2.3 and it failed to sign the dists with the import error below. I fixed it by changing the version to v2.1.1. 

I'm making this issue because I copied most of this workflow from the official [python packaging documentation](https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/#signing-the-distribution-packages) and they still have it set to v1.2.3 so it might be breaking a lot more workflows. 
<img width="523" alt="image" src="https://github.com/sigstore/gh-action-sigstore-python/assets/39905973/dfab256d-45dd-46ec-9ce9-ea5f9d327b71">

**Version**
v1.2.3

```
RUN:  /home/runner/work/_actions/sigstore/gh-action-sigstore-python/v1.2.3/action.py "./dist/*.tar.gz ./dist/*.whl"
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    GHA_SIGSTORE_PYTHON_IDENTITY_TOKEN: 
    GHA_SIGSTORE_PYTHON_SIGNATURE: 
    GHA_SIGSTORE_PYTHON_CERTIFICATE: 
    GHA_SIGSTORE_PYTHON_BUNDLE: 
    GHA_SIGSTORE_PYTHON_OIDC_CLIENT_ID: 
    GHA_SIGSTORE_PYTHON_OIDC_CLIENT_SECRET: 
    GHA_SIGSTORE_PYTHON_FULCIO_URL: 
    GHA_SIGSTORE_PYTHON_REKOR_URL: 
    GHA_SIGSTORE_PYTHON_CTFE: 
    GHA_SIGSTORE_PYTHON_REKOR_ROOT_PUBKEY: 
    GHA_SIGSTORE_PYTHON_STAGING: false
    GHA_SIGSTORE_PYTHON_VERIFY: false
    GHA_SIGSTORE_PYTHON_VERIFY_CERT_IDENTITY: 
    GHA_SIGSTORE_PYTHON_VERIFY_OIDC_ISSUER: 
    GHA_SIGSTORE_PYTHON_RELEASE_SIGNING_ARTIFACTS: false
    GHA_SIGSTORE_PYTHON_BUNDLE_ONLY: false
    GHA_SIGSTORE_PYTHON_INTERNAL_BE_CAREFUL_DEBUG: false
##[debug]/usr/bin/bash --noprofile --norc -e -o pipefail /home/runner/work/_temp/f66435f8-2a9b-4e0e-a833-a518666e3971.sh
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/runner/.local/lib/python3.10/site-packages/sigstore/__main__.py", line 20, in <module>
    from sigstore._cli import main
  File "/home/runner/.local/lib/python3.10/site-packages/sigstore/_cli.py", line 34, in <module>
    from sigstore._internal.rekor.client import (
  File "/home/runner/.local/lib/python3.10/site-packages/sigstore/_internal/rekor/__init__.py", line 19, in <module>
    from .client import RekorClient
  File "/home/runner/.local/lib/python3.10/site-packages/sigstore/_internal/rekor/client.py", line 33, in <module>
    from sigstore._internal.tuf import TrustUpdater
  File "/home/runner/.local/lib/python3.10/site-packages/sigstore/_internal/tuf.py", line 42, in <module>
    from tuf.ngclient import RequestsFetcher, Updater
  File "/home/runner/.local/lib/python3.10/site-packages/tuf/ngclient/__init__.py", line 14, in <module>
    from tuf.ngclient.updater import Updater
  File "/home/runner/.local/lib/python3.10/site-packages/tuf/ngclient/updater.py", line 48, in <module>
    from tuf.api.metadata import (
  File "/home/runner/.local/lib/python3.10/site-packages/tuf/api/metadata.py", line 56, in <module>
    from securesystemslib import keys as sslib_keys
ImportError: cannot import name 'keys' from 'securesystemslib' (/home/runner/.local/lib/python3.10/site-packages/securesystemslib/__init__.py)
```

**Comment by woodruffw** [comment] 2024-05-05 17:39
Thanks for the report! This looks like a transitive subdependency breakage, caused by `securesystemslib` changing their APIs.

We've fixed that as of 2.1.4 on sigstore-python itself: <https://github.com/sigstore/sigstore-python/blob/main/CHANGELOG.md#214>, but we aren't making new releases on the 1.x series anymore.

Given that, I think the best resolution here is probably to update the version referenced in the official Python docs or (better yet) remove it outright, since the separate action will become obsolete once [PEP 740](https://peps.python.org/pep-0740/) is complete. I can look into that.

**Comment by woodruffw** [comment] 2024-05-05 17:45
Filed https://github.com/pypa/packaging.python.org/pull/1539 for this upstream.

**Comment by woodruffw** [comment] 2024-05-06 21:51
Fixed in the docs upstream! Thanks @NotJoeMartinez!

**Closed by woodruffw** 2024-05-06 21:51 UTC
Labels: bug
